In [12]:
#load packages I need
import os
import tools
import scanpy as sc
import pandas as pd
import dandelion as ddl
from tqdm import tqdm
import matplotlib.pyplot as plt
import scanpy.external as sce
from matplotlib.pyplot import rc_context

In [13]:
#read in the file
data = sc.read_h5ad('/scratch/user/s4436039/scdata/Myeloid_Objects/NR_data_intersect.h5ad')

In [14]:
data

AnnData object with n_obs × n_vars = 623908 × 15074
    obs: 'nCount_RNA', 'nFeature_RNA', 'sample_type', 'cancer_type', 'patient_id', 'sample_id', 'percent.mt', 'site', 'sample_type_major', 'cancer_subtype', 'integration_id', 'ident', 'dataset_id'
    var: 'name'

In [15]:
data.obs

nCount_RNA  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                    20298.000000   
GSE215120_AM1_AAAGATGTCCAAATGC-1                     5574.000000   
GSE215120_AM1_AAAGTAGTCGGTGTTA-1                    13432.000000   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                    17143.000000   
GSE215120_AM1_AAATGCCGTTTGGCGC-1                     3603.000000   
...                                                          ...   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.871771   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.766977   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.133310   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -9.313746   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.476278   

                                                    nFeature_RNA sample_type  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                     3789.000000      tumour   
GSE215120_AM1_AAAGATGTCCAAATGC-1                     1721.000000      tumour   
GSE215120_AM1_AAAGTAGTCGGTGTTA-1                     2759.000000      tumour   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                     2659.000000      tumour   
GSE215120_AM1_AAATGCCGTTTGGCGC-1                     1012.000000      tumour   
...                                                          ...         ...   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...    -10.337130      Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -8.292435      Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -8.758132      Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -7.889039      Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...    -10.355681      Adnexa   

                                                       cancer_type  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                    Acral Melanoma   
GSE215120_AM1_AAAGATGTCCAAATGC-1                    Acral Melanoma   
GSE215120_AM1_AAAGTAGTCGGTGTTA-1                    Acral Melanoma   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                    Acral Melanoma   
GSE215120_AM1_AAATGCCGTTTGGCGC-1                    Acral Melanoma   
...                                                            ...   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   

                                                     patient_id  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                            AM1   
GSE215120_AM1_AAAGATGTCCAAATGC-1                            AM1   
GSE215120_AM1_AAAGTAGTCGGTGTTA-1                            AM1   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                            AM1   
GSE215120_AM1_AAATGCCGTTTGGCGC-1                            AM1   
...                                                         ...   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   

                                                                              sample_id  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                                GSE215120_Acral_MEL_AM1   
GSE215120_AM1_AAAGATGTCCAAATGC-1                                GSE215120_Acral_MEL_AM1   
GSE215120_AM1_AAAGTAGTCGGTGTTA-1                                GSE215120_Acral_MEL_AM1   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                                GSE215120_Acral_MEL_AM1   
GSE215120_AM1_AAATGCCGTTTGGCGC-1                                GSE215120_Acral_MEL_AM1   
...                                                                                 

In [16]:
# Check if the .raw attribute exists
if data.raw is not None:
    print("The AnnData object has a .raw attribute, which likely contains raw counts.")
else:
    print("The AnnData object does not have a .raw attribute. Raw counts may not be available.")

The AnnData object does not have a .raw attribute. Raw counts may not be available.


In [17]:
import numpy as np

In [18]:
# Inspect the data range
print("Range of .X values:", np.min(data.X), "to", np.max(data.X))

Range of .X values: 0.0 to 21387.0


In [19]:
# Extract the dataset_id column
dataset_ids = data.obs['dataset_id']

In [20]:
X_dense = data.X

In [23]:
# Loop through each unique dataset_id and calculate the range
for dataset_id in dataset_ids.unique():
    # Get the indices of cells belonging to the current dataset_id
    indices = dataset_ids == dataset_id

    # Subset the data matrix for these cells
    subset_X = X_dense[indices, :]

    # Calculate the range for the subset
    data_min = np.min(subset_X)
    data_max = np.max(subset_X)

    # Print the range for the current dataset_id
    print(f"Dataset ID {dataset_id}: Range of .X values is {data_min} to {data_max}")

Dataset ID GSE215120: Range of .X values is 0.0 to 1392.0
Dataset ID GSE199515: Range of .X values is 0.0 to 1191.0
Dataset ID GSE234933: Range of .X values is 0.0 to 13348.0
Dataset ID GSE154826: Range of .X values is 0.0 to 13329.0
Dataset ID GSE164690: Range of .X values is 0.0 to 4530.0
Dataset ID GSE176078: Range of .X values is 0.0 to 13141.0
Dataset ID GSE200218: Range of .X values is 0.0 to 6307.0
Dataset ID PRJCA005422: Range of .X values is 0.0 to 7978.0
Dataset ID GSE173468: Range of .X values is 0.0 to 4911.0
Dataset ID GSE195861: Range of .X values is 0.0 to 21387.0
Dataset ID GSE161529: Range of .X values is 0.0 to 8198.0
Dataset ID GSE231535: Range of .X values is 0.0 to 1575.0
Dataset ID GSE139324: Range of .X values is 0.0 to 4781.0
Dataset ID PMID32561858: Range of .X values is 0.0 to 8972.0
Dataset ID GSE225600: Range of .X values is 0.0 to 3021.0
Dataset ID GSE223063: Range of .X values is 0.0 to 6489.0
Dataset ID PRJNA907381: Range of .X values is 0.0 to 4358.0
Dat

In [3]:
data_clean = sc.read_h5ad('/scratch/user/s4436039/scdata/Python_Integration_Sep/NRclean_clustered2.h5ad')

In [13]:
data_clean

AnnData object with n_obs × n_vars = 498023 × 1268
    obs: 'nCount_RNA', 'nFeature_RNA', 'sample_type', 'cancer_type', 'patient_id', 'sample_id', 'percent.mt', 'site', 'sample_type_major', 'cancer_subtype', 'integration_id', 'ident', 'dataset_id', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'S_score', 'G2M_score', 'keep_or_remove', 'leiden', 'celltype', 'leiden_DC', 'leiden_DC_v2', 'exclude_annots', 'leiden_M', 'Technology', 'cancer_type_broad', 'clean-leiden_0.8', 'clean-subcluster', 'clean-subcluster-v2', 'YS_sig', 'HSC_sig', 'CD5nDC2_up_vDC3', 'DC3_up_vCD5nDC2', 'CD5pDC2_up_vDC3', 'DC3_up_vCD5pDC2', 'DC3_up_vMono', 'Mono_up_vDC3', 'DC1_sig', 'DC2_sig', 'DC3_sig', 'DC_Axl_sig', 'DC2_up_DC3', 'DC3_up_DC2', 'mregDC_sig', 'cDC1_mregDC', 'cDC2_mregDC', 'NR_annotati

In [14]:
data_clean.obs

nCount_RNA  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                    20298.000000   
GSE215120_AM1_AAAGATGTCCAAATGC-1                     5574.000000   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                    17143.000000   
GSE215120_AM1_ACACTGAAGATCCCGC-1                     5912.000000   
GSE215120_AM1_ACACTGATCCACTGGG-1                    18333.000000   
...                                                          ...   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.499666   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.871771   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.766977   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.133310   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -4.476278   

                                                    nFeature_RNA sample_type  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                     3789.000000      tumour   
GSE215120_AM1_AAAGATGTCCAAATGC-1                     1721.000000      tumour   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                     2659.000000      tumour   
GSE215120_AM1_ACACTGAAGATCCCGC-1                     1374.000000      tumour   
GSE215120_AM1_ACACTGATCCACTGGG-1                     2845.000000      tumour   
...                                                          ...         ...   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -9.853381      Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...    -10.337130      Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -8.292435      Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...     -8.758132      Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...    -10.355681      Adnexa   

                                                       cancer_type  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                    Acral Melanoma   
GSE215120_AM1_AAAGATGTCCAAATGC-1                    Acral Melanoma   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                    Acral Melanoma   
GSE215120_AM1_ACACTGAAGATCCCGC-1                    Acral Melanoma   
GSE215120_AM1_ACACTGATCCACTGGG-1                    Acral Melanoma   
...                                                            ...   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...           HGSOC   

                                                     patient_id  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                            AM1   
GSE215120_AM1_AAAGATGTCCAAATGC-1                            AM1   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                            AM1   
GSE215120_AM1_ACACTGAAGATCCCGC-1                            AM1   
GSE215120_AM1_ACACTGATCCACTGGG-1                            AM1   
...                                                         ...   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   
GSE180661_HGSOC_SPECTRUM-OV-045_S1_CD45P_LEFT_O...  Left Adnexa   

                                                                              sample_id  \
GSE215120_AM1_AAACCTGGTTGCTCCT-1                                GSE215120_Acral_MEL_AM1   
GSE215120_AM1_AAAGATGTCCAAATGC-1                                GSE215120_Acral_MEL_AM1   
GSE215120_AM1_AAATGCCCAGAGCCAA-1                                GSE215120_Acral_MEL_AM1   
GSE215120_AM1_ACACTGAAGATCCCGC-1                                GSE215120_Acral_MEL_AM1   
GSE215120_AM1_ACACTGATCCACTGGG-1                                GSE215120_Acral_MEL_AM1   
...                                                                                 

In [4]:
# Check if the .raw attribute exists
if data_clean.raw is not None:
    print("The AnnData object has a .raw attribute, which likely contains raw counts.")
else:
    print("The AnnData object does not have a .raw attribute. Raw counts may not be available.")

The AnnData object has a .raw attribute, which likely contains raw counts.


In [5]:
# Inspect the .raw attribute
print(data_clean.raw.X)

<Compressed Sparse Column sparse matrix of dtype 'float64'
	with 985128950 stored elements and shape (498023, 15074)>
  Coords	Values
  (1350, 0)	0.566099109104429
  (1680, 0)	0.9586734248858035
  (1713, 0)	1.5740773497880858
  (2151, 0)	0.3465509730938497
  (2283, 0)	0.7521607092580069
  (2579, 0)	1.0760647415217262
  (2584, 0)	0.55355529175207
  (3023, 0)	0.8183624838847489
  (6962, 0)	0.6881843912178163
  (7308, 0)	0.9216946001768674
  (11435, 0)	0.7519828754202119
  (11619, 0)	0.36750610828254576
  (11743, 0)	0.7753590767187828
  (12017, 0)	1.0214237469800223
  (13320, 0)	0.5311104638097615
  (14009, 0)	0.5057313826905775
  (15042, 0)	1.0661016855547676
  (17614, 0)	1.062742650729098
  (19032, 0)	0.35807331989940683
  (20660, 0)	0.7640344983735141
  (22673, 0)	1.098745639781789
  (22961, 0)	1.1057292785581059
  (28648, 0)	0.6126077727615333
  (29026, 0)	2.418138879075017
  (34064, 0)	1.5945653971802427
  :	:
  (497998, 15073)	2.7071173652136697
  (497999, 15073)	2.3395402679706945


In [7]:
# Compare a subset of data_clean from .X and .raw.X
print(data_clean.X[:5, :5])      # Normalized data_clean

[[ 0.61060864  0.37756366 -0.11434512 -0.21398202 -0.08800813]
 [-0.29090004  0.80172295 -0.12318421 -0.15191589 -0.06630305]
 [ 2.10042956 -0.38093311  2.62804255  5.07010836 -0.08303087]
 [ 3.29795736 -0.95451231 -0.12734503 -0.16111751 -0.06716711]
 [ 3.45275483  0.94410567  5.65023741  4.0639533  -0.08459465]]


In [8]:
print(data_clean.raw.X[:5, :5])  # Raw counts (if available)

<Compressed Sparse Column sparse matrix of dtype 'float64'
	with 0 stored elements and shape (5, 5)>


In [9]:
# Extract the dataset_id column
dataset_ids_clean = data_clean.obs['dataset_id']

In [10]:
X_dense_clean = data_clean.X

In [11]:
# Loop through each unique dataset_id and calculate the range
for dataset_id in dataset_ids_clean.unique():
    # Get the indices of cells belonging to the current dataset_id
    indices = dataset_ids_clean == dataset_id

    # Subset the data matrix for these cells
    subset_X = X_dense_clean[indices, :]

    # Calculate the range for the subset
    data_min = np.min(subset_X)
    data_max = np.max(subset_X)

    # Print the range for the current dataset_id
    print(f"Dataset ID {dataset_id}: Range of .X values is {data_min} to {data_max}")

Dataset ID GSE215120: Range of .X values is -6.374341625806664 to 10.0
Dataset ID GSE199515: Range of .X values is -5.29566266600097 to 10.0
Dataset ID GSE234933: Range of .X values is -9.32110017498897 to 10.0
Dataset ID GSE154826: Range of .X values is -6.430452819612501 to 10.0
Dataset ID GSE164690: Range of .X values is -6.988226590349096 to 10.0
Dataset ID GSE176078: Range of .X values is -8.334966890085449 to 10.0
Dataset ID GSE200218: Range of .X values is -7.739204349695556 to 10.0
Dataset ID PRJCA005422: Range of .X values is -8.702930199449623 to 10.0
Dataset ID GSE173468: Range of .X values is -6.968370406097011 to 10.0
Dataset ID GSE195861: Range of .X values is -10.0 to 10.0
Dataset ID GSE161529: Range of .X values is -10.0 to 10.0
Dataset ID GSE231535: Range of .X values is -10.0 to 10.0
Dataset ID GSE139324: Range of .X values is -6.33882584546033 to 10.0
Dataset ID PMID32561858: Range of .X values is -7.7767539234312295 to 10.0
Dataset ID GSE225600: Range of .X values i